### ISSUE TITLE
RMagick 2.13.3 ghost release?

### ISSUE THREAD

**Issue by kaspergrubbe** [rmagick-temp/rmagick#119]
I don't see it reflected anywhere in this repo or the changelog, what happened?

![screenie_1415976610_072921](https://cloud.githubusercontent.com/assets/334273/5047467/abf46ef0-6c0d-11e4-8b2e-8cf0be21f64c.png)

**Comment by bf4** [comment]
We are unable to regain control of this repository. Development has moved to https://github.com/gemhome/rmagick/

**Comment by kaspergrubbe** [comment]
@bf4 thanks.
