### ISSUE TITLE
Update repos project URL

### ISSUE THREAD

**Issue by itskingori** [rmagick-temp/rmagick#121]
Change the main link to this repo to the proper homepage.

![screen shot 2014-11-21 at 4 55 55 pm](https://cloud.githubusercontent.com/assets/703786/5144065/bf3590c4-719f-11e4-90ea-966a9febaf78.png)

It's currently set to [rmagick.rubyforge.org](http://rmagick.rubyforge.org/) while it should be [www.imagemagick.org/RMagick/doc](http://www.imagemagick.org/RMagick/doc/). Rubyforge no longer exists.

**Comment by bf4** [comment]
Please review https://github.com/rmagick/rmagick/issues/120  We have lost ownership of this repo

**Comment by itskingori** [comment]
Oh, I see. Ok. Thanks.
