### ISSUE TITLE
ImageList#append hangs

### ISSUE THREAD

**Issue by shviller** [rmagick-temp/rmagick#129]
`ImageList#append` and other methods that output a single `Image` (such as `#average`) hang when used after adding more than one image via `+=`, `#concat` or `<<`. For example:

```
require 'rmagick'

x = Magick::Image.new(1,1)
il = Magick::ImageList.new
il << x << x
il.append(false)
```

Reproduced on two Windows 7 x64 boxes, a NixOS one and an Android phone running Lil Debi in chroot. rmagick 2.13.4 on all of them. ImageMagick versions: 6.8.9-6 Q16 x86 on Windows, 6.8.9-9 Q16 arm on the phone, 6.9.0-0 Q16 x86-64 on NixOS. Ruby 1.9.3 everywhere, 64-bit everywhere except the phone.

**Comment by bf4** [comment]
Please close this issue as the repo has moved https://github.com/rmagick/rmagick/issues/120  At this time we do not have access to this repo.
