### ISSUE TITLE
Draw#get_type_metrics throws exception on leading @

### ISSUE THREAD

**Issue by latortuga** [rmagick-temp/rmagick#135]
``` ruby
> Magick::Version
=> "RMagick 2.15.0"

d = Magick::Draw.new
d.get_type_metrics("@") # => ArgumentError: no text to measure
d.get_type_metrics("@thing") # => ArgumentError: no text to measure
d.get_type_metrics("thing@") # => works
```

Is there some way for me to indicate that the leading @ is allowed? Is this a bug or intended?

**Comment by vassilevsky** [comment]
It's somewhere deep in the C extension. The function that does this is here:

https://github.com/gemhome/rmagick/blob/master/ext/RMagick/rmdraw.c#L1932

Your case is the first one (line 1951). But I couldn't quite spot an error right there. Perhaps it's deeper down in ImageMagick code (in the `Data_Get_Struct` macro).

Could you write a failing spec and send in a pull request to https://github.com/gemhome/rmagick (we haven't got access to this repo (yet))?

**Comment by bf4** [comment]
Please close this issue as the repo has moved https://github.com/rmagick/rmagick/issues/120  At this time we do not have access to this repo.
