### ISSUE TITLE
to_blob with SVG returns nil

### ISSUE THREAD

**Issue by DaveSanders** [rmagick-temp/rmagick#14]
I'm trying to do an in-memory conversion of an SVG string into a PNG.  I have to do it all in-memory because of my host (heroku) and needing to save the file blob out to AWS S3.

Here's the test code I'm trying to do.

im = Image.from_blob(self.image){self.format="svg"}
newim = im[0].to_blob(){format="png"}

self.image is just a string of SVG that I know works.  (I've tested it with a Image.write out to PNG which works)

im is ok, and shows the image is being loaded, however the im[0].to_blob is returning nil (with or without the format="png")

is this a bug?  Or am I doing something wrong?

thx

**Comment by DaveSanders** [comment]
Here is the self.image method with the svg to be able to test this.

def image
        return '<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="500" height="500"><desc>Created with Raphaël</desc><defs></defs><path fill="none" stroke="#006666" d="M0,0L0,500" style="stroke-width: 0.25px; " stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M25,0L25,500" style="stroke-width: 0.25px; " stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M50,0L50,500" style="stroke-width: 0.25px; " stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M75,0L75,500" style="stroke-width: 0.25px; " stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M100,0L100,500" style="stroke-width: 0.25px; " stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M125,0L125,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M150,0L150,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M175,0L175,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M200,0L200,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M225,0L225,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M250,0L250,500" style="stroke-width: 0.25px; "
         stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M275,0L275,500" style="stroke-width: 0.25px; "
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M300,0L300,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M325,0L325,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M350,0L350,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M375,0L375,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M400,0L400,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M425,0L425,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M450,0L450,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M475,0L475,500" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,0L500,0" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,25L500,25" style="stroke-width: 0.25px; "
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,50L500,50" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,75L500,75" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,100L500,100" style="stroke-width: 0.25px; "
         stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,125L500,125" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,150L500,150" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,175L500,175" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,200L500,200" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,225L500,225" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,250L500,250" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,275L500,275" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,300L500,300" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,325L500,325" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,350L500,350" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,375L500,375" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,400L500,400" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,425L500,425" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,450L500,450" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><path fill="none" stroke="#006666" d="M0,475L500,475" style="stroke-width: 0.25px; " 
        stroke-width="0.25"></path><text x="200" y="205" text-anchor="middle" style="text-anchor: middle; font: normal 
        normal normal 16px/normal Courier; font-style: italic; font-weight: bold; " font="16px Courier" stroke="none" 
        fill="#0000ff" font-style="italic" font-weight="bold"><tspan>testing text</tspan></text><rect x="50" y="50" width="100" 
        height="100" r="0" rx="0" ry="0" fill="#c0c0c0" stroke="#000000"></rect><circle cx="150" cy="100" r="3" fill="#00ff00" 
        stroke="#000"></circle><circle cx="50" cy="100" r="3" fill="#00ff00" stroke="#000"></circle><circle cx="100" cy="50" r="3" 
        fill="#00ff00" stroke="#000"></circle><circle cx="100" cy="150" r="3" fill="#00ff00" stroke="#000"></circle></svg>'
    end

**Comment by DaveSanders** [comment]
Well, apparently I was doing it wrong. :)

Here's code that works.  A lot easier than my head was trying to do it:

```
    im = Magick::Image::from_blob(self.image){self.format="svg"}
    im[0].format = 'png'
            im[0].to_blob
```

closing the issue.

**Comment by rpocklington** [comment]
I'm trying to do the exact same thing DaveSanders was attempting.

The documentation supports the method DaveSanders was using.
For that matter, calling `im[0].to_blob` without specifying a format also returns `nil` for me. This is very strange since the format is being specified when the `Image` object is generated by specifying `format` on the `from_blob` method.

I'm grateful for the workaround DaveSanders provided. I am able to get it to work by specifying the format on the `Image` object before calling `to_blob`.

However, I consider this a defect and believe it should be reopened.
