### ISSUE TITLE
RMagick & Rails performance

### ISSUE THREAD

**Issue by rnhurt** [rmagick-temp/rmagick#29]
I have a question on [Server Fault](http://serverfault.com/questions/291151/ec2-nginx-passenger-performance-is-horrible) where I'm having problems with RMagick consuming all CPU resources, but I thought I would ask the experts here some more pointed questions.  I have a very simple one liner that can consume all 8 ECUs on a extra large Amazon server:

```
image = Magick::Image.read("pattern:checkerboard") { self.size = "400x400" }.first
image.format = "jpg"
send_data image.to_blob 
```

Running ApacheBench (ab -n 100 -c 10 "http://my.aws.box/checkerboard") causes the box to consume all 8 CPUs for 15 seconds.  It almost acts as if RMagick is single threaded and can't process more than one thing at a time.  But if I run it with one concurrent request the CPUs all get part of the load but don't fill up completely.

I'm really stumped by this RMagick performance and am grasping at straws.  Any help at all would be appreciated.  :)

**Comment by mmaiza** [comment]
Try the following, disable ImageMagick internal threading. You would need to re-compile and re-install. Run configure as follows "configure --disable-openmp". I suspect that this maybe the issue.

Moncef Maiza

-----Original Message-----
From: rnhurt [mailto:reply@reply.github.com] 
Sent: Sunday, July 17, 2011 4:17 PM
To: moncef@datasieve.com
Subject: [rmagick] RMagick & Rails performance (#29)

I have a question on [Server Fault](http://serverfault.com/questions/291151/ec2-nginx-passenger-performance-is-horrible) where I'm having problems with RMagick consuming all CPU resources, but I thought I would ask the experts here some more pointed questions.  I have a very simple one liner that can consume all 8 ECUs on a extra large Amazon server:

```
image = Magick::Image.read("pattern:checkerboard") { self.size = "400x400" }.first
image.format = "jpg"
send_data image.to_blob 
```

Running ApacheBench (ab -n 100 -c 10 "http://my.aws.box/checkerboard") causes the box to consume all 8 CPUs for 15 seconds.  It almost acts as if RMagick is single threaded and can't process more than one thing at a time.  But if I run it with one concurrent request the CPUs all get part of the load but don't fill up completely.

I'm really stumped by this RMagick performance and am grasping at straws.  Any help at all would be appreciated.  :)

## 

Reply to this email directly or view it on GitHub:
https://github.com/rmagick/rmagick/issues/29

**Comment by rnhurt** [comment]
Yes, I recompiled and performance shot up.  OK, for future generations, running RMagick on AWS with multiple cores doesn't work (well) unless you disable OpenMP.  I could literally respond to more requests with a single ECU than with 16 ECUs.  Amazing!  I also turned the quality down to 8bit to squeeze out a bit more performance.

Later...
  Richard
