### ISSUE TITLE
Scale doesn't work

### ISSUE THREAD

**Issue by DennisTheMenace** [rmagick-temp/rmagick#32]
In my ruby code I'm just using this
"
require 'RMagick'

clown = Magick::Image.read("clown.jpg").first
clown.scale(125,125)
clown.write('crop_resized.jpg')
"

But the outputted image is the same size.

Help me!

Regards Joshua

**Comment by mattneub** [comment]
Surely you mean clown = clown.scale(125,125). If you don't capture the scaled output, you're just throwing it away.

**Comment by DennisTheMenace** [comment]
I'm an idiot!
