### ISSUE TITLE
Does not install on Mac OS X 10.7.2 and Ruby 1.9.3-p0

### ISSUE THREAD

**Issue by sekrett** [rmagick-temp/rmagick#36]
<pre>Installing rmagick (2.13.1) with native extensions 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /Users/sekrett/.rvm/rubies/ruby-1.9.3-p0/bin/ruby extconf.rb 
checking for Ruby version >= 1.8.5... yes
extconf.rb:128: Use RbConfig instead of obsolete and deprecated Config.
checking for clang... yes
checking for Magick-config... yes
checking for ImageMagick version >= 6.4.9... yes
checking for HDRI disabled version of ImageMagick... yes
checking for stdint.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.</pre>

**Comment by mmaiza** [comment]
Alexander,
Rmagick definitely installs on Mac OS. I would not know without seeing all your steps and the logs but chances are you are missing some libraries.

Follow the steps and guidelines described by http://rmagick.rubyforge.org/install-osx.html.

Moncef

-----Original Message-----
From: Alexander Zubkov [mailto:reply@reply.github.com] 
Sent: Saturday, November 05, 2011 10:04 AM
To: mmaiza
Subject: [rmagick] Does not install on Mac OS X 10.7.2 and Ruby 1.9.3-p0 (#36)

<pre>Installing rmagick (2.13.1) with native extensions 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /Users/sekrett/.rvm/rubies/ruby-1.9.3-p0/bin/ruby extconf.rb 
checking for Ruby version >= 1.8.5... yes
extconf.rb:128: Use RbConfig instead of obsolete and deprecated Config.
checking for clang... yes
checking for Magick-config... yes
checking for ImageMagick version >= 6.4.9... yes
checking for HDRI disabled version of ImageMagick... yes
checking for stdint.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.</pre>


---

Reply to this email directly or view it on GitHub:
https://github.com/rmagick/rmagick/issues/36

**Comment by sekrett** [comment]
It installs on Ruby 1.9.2-p290, but not on 1.9.3-p0. I don't think it is because of missing libraries. If you can read, RbConfig and Config - it is Ruby classes. The old Config has been deprecated and has to be replaced with RbConfig.

**Comment by mmaiza** [comment]
I will take a closer look, thanks.

Moncef

-----Original Message-----

**Comment by dburrows** [comment]
+1 on this, OS X 1.7.2, Ruby 1.9.3-p0 via RVM, XCode 4.2 via AppStore, re-installed imagemagic via homebrew, still get error below
seems there's some issues with Xcode 4.2 moving to clang, (tried installing https://github.com/kennethreitz/osx-gcc-installer on a seperate machine but still no luck, exact same error as below)

```
gem install rmagick
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
    ERROR: Failed to build gem native extension.

        /Users/david/.rvm/rubies/ruby-1.9.3-p0/bin/ruby extconf.rb
checking for Ruby version >= 1.8.5... yes
checking for /usr/bin/gcc... yes
checking for Magick-config... yes
checking for ImageMagick version >= 6.4.9... yes
checking for HDRI disabled version of ImageMagick... yes
checking for stdint.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/david/.rvm/rubies/ruby-1.9.3-p0/bin/ruby
/Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:506:in `try_cpp'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:931:in `block in have_header'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:930:in `have_header'
    from extconf.rb:193:in `<main>'
```

**Comment by dburrows** [comment]
+1 on this, ruby-1.9.3-p0 through RVM, XCode 4.2, Lion 7.2, ImageMagick via Homebrew, bundler fails with following error

```
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /Users/david/.rvm/rubies/ruby-1.9.3-p0/bin/ruby extconf.rb 
checking for Ruby version >= 1.8.5... yes
checking for gcc-4.2... yes
checking for Magick-config... yes
checking for ImageMagick version >= 6.4.9... yes
checking for HDRI disabled version of ImageMagick... yes
checking for stdint.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/david/.rvm/rubies/ruby-1.9.3-p0/bin/ruby
/Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:506:in `try_cpp'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:931:in `block in have_header'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:254:in `open'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
    from /Users/david/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/mkmf.rb:930:in `have_header'
    from extconf.rb:193:in `<main>'


Gem files will remain installed in /Users/david/.rvm/gems/ruby-1.9.3-p0/gems/rmagick-2.13.1 for inspection.
Results logged to /Users/david/.rvm/gems/ruby-1.9.3-p0/gems/rmagick-2.13.1/ext/RMagick/gem_make.out
An error occured while installing rmagick (2.13.1), and Bundler cannot continue.
Make sure that `gem install rmagick -v '2.13.1'` succeeds before bundling.
```

**Comment by dburrows** [comment]
got this workaround from http://stackoverflow.com/questions/7961091/mac-rmagick-wont-install-with-xcode-4-2/7973760#7973760

remove imagemagick and reinstall using 

```
brew install imagemagick --disable-openmp
```

then install rmagick - everything worked for me then

**Comment by Burgestrand** [comment]
^ worked for me too (Lion, XCode 4.2, 1.9.3-p0).

**Comment by antlypls** [comment]
dburrows's workaround worked for me on Lion 10.7.2, XCode 4.2, 1.9.2-p290

**Comment by vijjunyros** [comment]
I need rmagick in windows xp

**Comment by mmaiza** [comment]
If you look at the bottom of the thread you will see that one suggested solution is to re-install imagemagick without openmp. It seems that recent versions of OS X have buggy implementations of openmp. This should be fine for most common rmagick operations. There is nothing I can do on the rmagick side as this is an OS X issue.

Moncef

-----Original Message-----

**Comment by sekrett** [comment]
Why don't you try something like this?
https://github.com/cucumber/gherkin/commit/45d572fc4188a4e2d0b0769e9e9be33431c37bb2
It is related to Ruby, not ImageMagick.

**Comment by ac74394** [comment]
ImageMagick also does not install on Ubuntu Server 10.04(LTS) with Ruby 1.9.3.  Both Ubuntu and Ruby are fresh installs as of this AM.  All Ruby 1.9.2 dependencies have been met.

**Comment by mmaiza** [comment]
I have installed it on Ubuntu directly using the gem as well as directly by compiling using setup.rb. In both cases it works.  I do not really have the time to look into OS X but nothing in ruby/rmagick should prevent you from installing if you straighten out the 'C' libraries. The deprecation issue will be addressed later but deprecated does not mean removed it means it will be in some future.
I am closing this issue for now since there is a workaround.

**Comment by bogartjordan** [comment]
Hello All, I tried the fix listed above, but that generates a different error for me -- is there any final or correct fix for this issue?

**Comment by bogartjordan** [comment]
After much frustration I got rmagick to work. Here is what I did:

-- removed xcode 4.3.1
-- removed complete rails build, removed all gems
-- installed xcode 4.2.1
-- installed gcc 4.2
-- reinstalled rails stack
-- ran bundle install

Running Lion and Ruby 1.9.3p125

back to work ;)

**Comment by alx** [comment]
+1 on this, dburrows workaround worked for me.

```
brew remove imagemagick
brew install imagemagick --disable-openmp --from-source
```

Build from source to solve a current issue with homebrew libtiff.

**Comment by wrodenbusch** [comment]
+1 dburrows workaround

**Comment by franzejr** [comment]
Problem solved with:
brew remove imagemagick
brew install imagemagick --disable-openmp --from-source
bundle install

Running on Mac OS X Lion.
= )

**Comment by Hai-Lin** [comment]
I am running on OS 10.7 with Xcode 4.3.3 (4E3002). I tried all the things---brew, build from source.
Only this works----https://github.com/maddox/magick-installer

**Comment by seanrafferty** [comment]
+1 dburrows workaround

**Comment by janotterstetter** [comment]
jap, +1 dburrows workaround for lion with xcode 4.3.x

**Comment by jsullivan** [comment]
+1 for dburrows workaround with Mountain Lion and Xcode 4.4

**Comment by zernel** [comment]
It works. Thanks alx.

**Comment by codyeatworld** [comment]
```
brew remove imagemagick
brew install imagemagick --disable-openmp --from-source
bundle install
```

This worked for me! os x 10.8.2, command line tools and gcc, no xcode.

**Comment by sfsekaran** [comment]
In order to run homebrew from source, you'll have to use the `--build-from-source` option now:

```
brew install imagemagick --disable-openmp --build-from-source
```
