### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by thomasguillory** [rmagick-temp/rmagick#37]
Hi,

I'm trying to convert a JPG to a PNG with a percentage of translucency. Here the code I've so far :

```
require 'RMagick'
image = Magick::Image.read(t.img.path).first
image.format = 'PNG'
image.background_color = 'none'
image.alpha(Magick::ActivateAlphaChannel)
image.matte = true
image.opacity = (Magick::TransparentOpacity - Magick::OpaqueOpacity) * (1.0 - alpha.to_f)

send_data image.to_blob,
  :filename => "texture__#{params[:id]}_alpha_#{params[:alpha]}.png",
  :disposition => 'inline',
  :type => "image/png"
```

I tried all things : alpha, matte, ... Nothing to do, to_blob return each time the image with no translucency. When exploring the code, I've noted a comment (on the image_opacity exemple) : "Replace use of #opacity attribute (which doesn't seem to be working) … [rmagick]"

**Comment by mmaiza** [comment]
This is fairly standard and they are several ways to do. Assuming that t.img.path is the path to an image where you are specify the image type i.e. .jpg or .gif or .png... You can try this:

```
require 'RMagick'

image = Magick::Image.read(t.img.path).first

# Magick::MaxRGB is 100% transparent, 0 is opaque
send_data(image.to_blob {self.format = 'PNG'; self.quality = 100; self.opacity = Magick::MaxRGB/2},
  :filename => "texture__#{params[:id]}_alpha_#{params[:alpha]}.png",
  :disposition => 'inline',
  :type => "img/png")
```

Moncef

-----Original Message-----
From: Artimuz [mailto:reply@reply.github.com] 
Sent: Friday, November 25, 2011 6:26 AM
To: mmaiza
Subject: [rmagick] Opacity (#37)

Hi,

I'm trying to convert a JPG to a PNG with a percentage of translucency. Here the code I've so far :

```
require 'RMagick'
image = Magick::Image.read(t.img.path).first
image.format = 'PNG'
image.background_color = 'none'
image.alpha(Magick::ActivateAlphaChannel)
image.matte = true
image.opacity = (Magick::TransparentOpacity - Magick::OpaqueOpacity) * (1.0 - alpha.to_f)

send_data image.to_blob,
  :filename => "texture__#{params[:id]}_alpha_#{params[:alpha]}.png",
  :disposition => 'inline',
  :type => "image/png"
```

I tried all things : alpha, matte, ... Nothing to do, to_blob return each time the image with no translucency. When exploring the code, I've noted a comment (on the image_opacity exemple) : "Replace use of #opacity attribute (which doesn't seem to be working) … [rmagick]"

---

Reply to this email directly or view it on GitHub:
https://github.com/rmagick/rmagick/issues/37

**Comment by thomasguillory** [comment]
OK, thanks for the trick.

But in my opinion, there is something weird in this approach : why is opacity working only in the to_blob code block ? With other params, like format, I can work outside.

Furthermore, I didn't see any clue of that in the documentation ([opacity](http://studio.imagemagick.org/RMagick/doc/imageattrs.html#opacity), [to_blob](http://studio.imagemagick.org/RMagick/doc/image3.html#to_blob)).

Finally, I believe that Magick::MaxRGB has been replaced with Magick::QuantumRange in v2, isn't it ?

**Comment by mmaiza** [comment]
I just gave you a pointer to show you that opacity works for all rmagick versions. Your issues were mainly due to bad syntax. Doing image.opacity or self.opacity is one and the same as this is just standard Ruby. I used MaxRGB because I did not know what  version you were using. If you are using version 2+ then use QuantumRange (they are the same for now). Since this is resolved I am closing it.
