### ISSUE TITLE
Can't rotate text

### ISSUE THREAD

**Issue by stephenprater** [rmagick-temp/rmagick#42]
``` ruby
il = ImageList.new
(1..100).each do |t|
  i = Image.new(100,100)
  d = Draw.new
  d.rotate(t)
  d.annotate(i,0,0,0,0,'test') { self.gravity = CenterGravity; self.fill = "black" }
  il << i
end
il.montage.write('test.png')
```

Does not rotate text.
Neither does calling "annotate" with rotation argument (nominally the first two in the call.
Neither does setting the "affine" attribute on the Draw Object.
Neither does anything else I can think to try.

(I can rotate the image, of course - but it seems like the text should be rotatable without having to composite together two images.)

**Comment by rmagick-temp** [comment]
You are a bit off. You can add an annotation and then rotate it. You can do something like this:

img = Image.new(300,300) do |i|
  i.background_color = 'blue'
end
Draw.new.annotate(img, 0,0,0,40, 'Text Sample') {
  self.font_family = 'Helvetica'
  self.fill = 'white'
  self.stroke = 'transparent'
  self.pointsize = 32
  self.rotation = 30
}
img.display

Remember that once you add text or some drawing object to a rasterized images you cannot usually perform operations on it. You must do it before. Now SVG on the other hand gives you a lot more control.

Regards,
Moncef Maiza

-----Original Message-----
From: Stephen Prater [mailto:reply@reply.github.com] 
Sent: Friday, January 20, 2012 7:44 PM
To: rmagick
Subject: [rmagick] Can't rotate text (#42)

``` ruby
il = ImageList.new
(1..100).each do |t|
  i = Image.new(100,100)
  d = Draw.new
  d.rotate(t)
  d.annotate(i,0,0,0,0,'test') { self.gravity = CenterGravity; self.fill = "black" }
  il << i
end
il.montage.write('test.png')
```

Does not rotate text.
Neither does calling "annotate" with rotation argument (nominally the first two in the call.
Neither does setting the "affine" attribute on the Draw Object.
Neither does anything else I can think to try.

(I can rotate the image, of course - but it seems like the text should be rotatable without having to composite together two images.)

---

Reply to this email directly or view it on GitHub:
https://github.com/rmagick/rmagick/issues/42

**Comment by stephenprater** [comment]
Yep, that was it.

**Comment by r00takaspin** [comment]
yes, it works, thanks!
