### ISSUE TITLE
Rmagick 1.15.17 doesn't work with ree 

### ISSUE THREAD

**Issue by dhirengupta** [rmagick-temp/rmagick#48]
I get the following error. Please help.

Fetching: rmagick-1.15.17.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
    ERROR: Failed to build gem native extension.

```
    /Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/bin/ruby gem_extconf.rb
```

sh configure 

Configuring RMagick 1.15.17
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking for ruby... /Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/bin/ruby
checking Ruby version... 1.8.7
checking for Magick-config... Magick-config
checking ImageMagick version... 6.7.5
checking for library containing InitializeMagick... none required
checking for snprintf... yes
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for sys/types.h... (cached) yes
checking for AcquireMagickMemory... yes
checking for AcquireStringInfo... yes
checking for AdaptiveBlurImageChannel... yes
checking for AdaptiveResizeImage... yes
checking for AdaptiveSharpenImage... yes
checking for AdaptiveThresholdImage... yes
checking for AddDefinitions... no
checking for AddNoiseImageChannel... yes
checking for AllocateImageProfileIterator... no
checking for BilevelImageChannel... yes
checking for BlackThresholdImage... yes
checking for BlurImageChannel... yes
checking for ClearMagickException... yes
checking for CompareImageChannels... yes
checking for CompareImageLayers... yes
checking for CompositeImageChannel... yes
checking for ContrastStretchImageChannel... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating ext/RMagick/extconf.rb
config.status: creating metaconfig
config.status: creating ext/RMagick/rmagick_config.h
configure:

This installation of RMagick 1.15.17 is configured for ruby 1.8.7 (2012-02-08 MBARI 8/0x6770 on patchlevel 358) [i686-darwin11.3.0], MBARI 0x6770, Ruby Enterprise Edition 2012.02 and ImageMagick 6.7.5.
RMagick configuration completed successfully.

make
if test -n "/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/lib"; then \
        RUBYLIBDIR=--rbdir="/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/lib"; \
    fi; \
    if test -n "/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/lib"; then \
        RUBYARCHDIR=--sodir="/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/lib"; \
    fi; \
    /Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/bin/ruby setup.rb config $RUBYLIBDIR $RUBYARCHDIR --data-dir=/share
---> lib
---> lib/rvg
<--- lib/rvg
<--- lib
---> ext
---> ext/RMagick
/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/bin/ruby /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/ext/RMagick/extconf.rb
creating Makefile
<--- ext/RMagick
<--- ext
/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/bin/ruby setup.rb setup
---> lib
---> lib/rvg
<--- lib/rvg
<--- lib
---> ext
---> ext/RMagick
make
/usr/bin/gcc-4.2  -I. -I/opt/local/include -I/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/i686-darwin11.3.0 -I/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/i686-darwin11.3.0 -I/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/ext/RMagick -DRUBY_VERSION=0x187  -I/usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick   -fno-common   -c rmdraw.c
rmdraw.c: In function ‘Draw_annotate’:
rmdraw.c:448: warning: ‘InterpretImageAttributes’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:96)
rmdraw.c: In function ‘get_dummy_tm_img’:
rmdraw.c:1419: warning: ‘AllocateImage’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:122)
rmdraw.c: In function ‘get_type_metrics’:
rmdraw.c:1504: warning: ‘InterpretImageAttributes’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:96)
/usr/bin/gcc-4.2  -I. -I/opt/local/include -I/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/i686-darwin11.3.0 -I/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/i686-darwin11.3.0 -I/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/ext/RMagick -DRUBY_VERSION=0x187  -I/usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick   -fno-common   -c rmfill.c
rmfill.c: In function ‘point_fill’:
rmfill.c:132: warning: ‘SetImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:257)
rmfill.c:144: warning: ‘SyncImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:217)
rmfill.c: In function ‘vertical_fill’:
rmfill.c: In function ‘point_fill’:
rmfill.c:132: warning: ‘SetImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:257)
rmfill.c:144: warning: ‘SyncImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:217)
rmfill.c: In function ‘vertical_fill’:
rmfill.c:210: warning: ‘SetImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:257)
rmfill.c:216: warning: ‘SyncImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:217)
rmfill.c: In function ‘horizontal_fill’:
rmfill.c:280: warning: ‘SetImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:257)
rmfill.c:285: warning: ‘SyncImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:217)
rmfill.c: In function ‘v_diagonal_fill’:
rmfill.c:354: warning: ‘SetImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:257)
rmfill.c:366: warning: ‘SyncImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:217)
rmfill.c: In function ‘h_diagonal_fill’:
ruby: unable to read font `/usr/local/share/ghostscript/fonts/n019003l.pfb' @ error/annotate.c/RenderFreetype/1120.
ruby: Postscript delegate failed`/var/folders/b8/29641ny50sl9bpjrq2630qj40000gn/T/magick-mx5T0Bx9': No such file or directory @ error/ps.c/ReadPSImage/830.
/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/misc.rb:321:in `get_type_metrics': Can't measure text. Are the fonts installed? Is the FreeType library installed? (RuntimeError)
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/misc.rb:321:in`render'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/misc.rb:696:in `text'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/text.rb:65:in`add_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:264:in `add_outermost_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:264:in`each'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:264:in `add_outermost_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:236:in`draw'
    from OrigCoordSys.rb:17
post-setup.rb: OrigCoordSys.rb example returned error code 256
/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/bin/ruby -I /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib -I /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./ext/RMagick PreserveAspectRatio.rb (example 5 of 183)
ruby: unable to read font `/usr/local/share/ghostscript/fonts/n019003l.pfb' @ error/annotate.c/RenderFreetype/1120.
ruby: Postscript delegate failed`/var/folders/b8/29641ny50sl9bpjrq2630qj40000gn/T/magick-FcJlP2fY': No such file or directory @ error/ps.c/ReadPSImage/830.
/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/misc.rb:321:in `get_type_metrics': Can't measure text. Are the fonts installed? Is the FreeType library installed? (RuntimeError)
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/misc.rb:321:in`render'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/misc.rb:696:in `text'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/text.rb:65:in`add_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/container.rb:72:in `add_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/container.rb:72:in`each'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/container.rb:72:in `add_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/container.rb:72:in`add_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/container.rb:72:in `each'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/container.rb:72:in`add_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:264:in `add_outermost_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:264:in`each'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:264:in `add_outermost_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:236:in`draw'
    from RotateScale.rb:36
setup.rb:             Too many examples failed. Search for "Help!" at
            http://rmagick.rubyforge.org/install-faq.html.
post-setup.rb: RotateScale.rb example returned error code 256
make: **\* [all] Error 1
Gem files will remain installed in /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17 for inspection.
Results logged to /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./gem_make.

I can install rmagick latest version but I need to install rmagick 1.15.17.  Please help

**Comment by rmagick-temp** [comment]
It looks like you are missing some libraries. My experience with REE is that they restrict the repositories and thus you will have to identify which reps will contain the font libraries and such. Please refer to:

http://rmagick.rubyforge.org/install-faq.html#linux

Moncef

-----Original Message-----
From: Dhiren Gupta [mailto:reply@reply.github.com] 
Sent: Wednesday, March 07, 2012 11:09 AM
To: rmagick
Subject: [rmagick] Rmagick 1.15.17 doesn't work with ree (#48)

I get the following error. Please help.

Fetching: rmagick-1.15.17.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
    ERROR: Failed to build gem native extension.

```
    /Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/bin/ruby gem_extconf.rb
```

sh configure 

Configuring RMagick 1.15.17
checking for gcc... gcc
checking for C compiler default output file name... a.out checking whether the C compiler works... yes checking for ruby... /Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/bin/ruby
checking Ruby version... 1.8.7
checking for Magick-config... Magick-config checking ImageMagick version... 6.7.5 checking for library containing InitializeMagick... none required checking for snprintf... yes checking how to run the C preprocessor... gcc -std=gnu99 -E checking for grep that handles long lines and -e... /usr/bin/grep checking for egrep... /usr/bin/grep -E checking for ANSI C header files... yes checking for sys/types.h... yes checking for sys/stat.h... yes checking for stdlib.h... yes checking for string.h... yes checking for memory.h... yes checking for strings.h... yes checking for inttypes.h... yes checking for stdint.h... yes checking for unistd.h... yes checking for sys/types.h... (cached) yes checking for AcquireMagickMemory... yes checking for AcquireStringInfo... yes checking for AdaptiveBlurImageChannel... yes checking for AdaptiveResizeImage... yes checking for AdaptiveSharpenImage... yes checking for AdaptiveThresholdImage... yes checking for AddDefinitions... no checking for AddNoiseImageChannel... yes checking for AllocateImageProfileIterator... no checking for BilevelImageChannel... yes checking for BlackThresholdImage... yes checking for BlurImageChannel... yes checking for ClearMagickException... yes checking for CompareImageChannels... yes checking for CompareImageLayers... yes checking for CompositeImageChannel... yes checking for ContrastStretchImageChannel... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating ext/RMagick/extconf.rb
config.status: creating metaconfig
config.status: creating ext/RMagick/rmagick_config.h
configure:

This installation of RMagick 1.15.17 is configured for ruby 1.8.7 (2012-02-08 MBARI 8/0x6770 on patchlevel 358) [i686-darwin11.3.0], MBARI 0x6770, Ruby Enterprise Edition 2012.02 and ImageMagick 6.7.5.
RMagick configuration completed successfully.

make
if test -n "/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/lib"; then \
        RUBYLIBDIR=--rbdir="/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/lib"; \
    fi; \
    if test -n "/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/lib"; then \
        RUBYARCHDIR=--sodir="/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/lib"; \
    fi; \
    /Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/bin/ruby setup.rb config $RUBYLIBDIR $RUBYARCHDIR --data-dir=/share
---> lib
---> lib/rvg
<--- lib/rvg
<--- lib
---> ext
---> ext/RMagick
/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/bin/ruby /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/ext/RMagick/extconf.rb
creating Makefile
<--- ext/RMagick
<--- ext
/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/bin/ruby setup.rb setup
---> lib
---> lib/rvg
<--- lib/rvg
<--- lib
---> ext
---> ext/RMagick
make
/usr/bin/gcc-4.2  -I. -I/opt/local/include -I/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/i686-darwin11.3.0 -I/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/i686-darwin11.3.0 -I/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/ext/RMagick -DRUBY_VERSION=0x187  -I/usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick   -fno-common   -c rmdraw.c
rmdraw.c: In function ‘Draw_annotate’:
rmdraw.c:448: warning: ‘InterpretImageAttributes’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:96)
rmdraw.c: In function ‘get_dummy_tm_img’:
rmdraw.c:1419: warning: ‘AllocateImage’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:122)
rmdraw.c: In function ‘get_type_metrics’:
rmdraw.c:1504: warning: ‘InterpretImageAttributes’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:96)
/usr/bin/gcc-4.2  -I. -I/opt/local/include -I/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/i686-darwin11.3.0 -I/Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/lib/ruby/1.8/i686-darwin11.3.0 -I/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/ext/RMagick -DRUBY_VERSION=0x187  -I/usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick   -fno-common   -c rmfill.c
rmfill.c: In function ‘point_fill’:
rmfill.c:132: warning: ‘SetImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:257)
rmfill.c:144: warning: ‘SyncImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:217)
rmfill.c: In function ‘vertical_fill’:
rmfill.c: In function ‘point_fill’:
rmfill.c:132: warning: ‘SetImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:257)
rmfill.c:144: warning: ‘SyncImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:217)
rmfill.c: In function ‘vertical_fill’:
rmfill.c:210: warning: ‘SetImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:257)
rmfill.c:216: warning: ‘SyncImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:217)
rmfill.c: In function ‘horizontal_fill’:
rmfill.c:280: warning: ‘SetImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:257)
rmfill.c:285: warning: ‘SyncImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:217)
rmfill.c: In function ‘v_diagonal_fill’:
rmfill.c:354: warning: ‘SetImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:257)
rmfill.c:366: warning: ‘SyncImagePixels’ is deprecated (declared at /usr/local/Cellar/imagemagick/6.7.5-7/include/ImageMagick/magick/deprecate.h:217)
rmfill.c: In function ‘h_diagonal_fill’:
ruby: unable to read font `/usr/local/share/ghostscript/fonts/n019003l.pfb' @ error/annotate.c/RenderFreetype/1120.
ruby: Postscript delegate failed`/var/folders/b8/29641ny50sl9bpjrq2630qj40000gn/T/magick-mx5T0Bx9': No such file or directory @ error/ps.c/ReadPSImage/830.
/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/misc.rb:321:in `get_type_metrics': Can't measure text. Are the fonts installed? Is the FreeType library installed? (RuntimeError)
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/misc.rb:321:in`render'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/misc.rb:696:in `text'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/text.rb:65:in`add_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:264:in `add_outermost_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:264:in`each'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:264:in `add_outermost_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:236:in`draw'
    from OrigCoordSys.rb:17
post-setup.rb: OrigCoordSys.rb example returned error code 256 /Users/dhirengupta/.rvm/rubies/ree-1.8.7-2012.02/bin/ruby -I /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib -I /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./ext/RMagick PreserveAspectRatio.rb (example 5 of 183)
ruby: unable to read font `/usr/local/share/ghostscript/fonts/n019003l.pfb' @ error/annotate.c/RenderFreetype/1120.
ruby: Postscript delegate failed`/var/folders/b8/29641ny50sl9bpjrq2630qj40000gn/T/magick-FcJlP2fY': No such file or directory @ error/ps.c/ReadPSImage/830.
/Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/misc.rb:321:in `get_type_metrics': Can't measure text. Are the fonts installed? Is the FreeType library installed? (RuntimeError)
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/misc.rb:321:in`render'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/misc.rb:696:in `text'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/text.rb:65:in`add_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/container.rb:72:in `add_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/container.rb:72:in`each'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/container.rb:72:in `add_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/container.rb:72:in`add_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/container.rb:72:in `each'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/container.rb:72:in`add_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:264:in `add_outermost_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:264:in`each'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:264:in `add_outermost_primitives'
    from /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./lib/rvg/rvg.rb:236:in`draw'
    from RotateScale.rb:36
setup.rb:             Too many examples failed. Search for "Help!" at
            http://rmagick.rubyforge.org/install-faq.html.
post-setup.rb: RotateScale.rb example returned error code 256
make: **\* [all] Error 1
Gem files will remain installed in /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17 for inspection.
Results logged to /Users/dhirengupta/.rvm/gems/ree-1.8.7-2012.02@kg/gems/rmagick-1.15.17/./gem_make.out

---

Reply to this email directly or view it on GitHub:
https://github.com/rmagick/rmagick/issues/48

**Comment by dhirengupta** [comment]
I have installed the delegate libraries given in http://rmagick.rubyforge.org/install-faq.html#linux and now I can install rmagick 1.15.17. Thanks a lot Moncef

Dhiren
