### ISSUE TITLE
what is going on?

### ISSUE THREAD

**Issue by deunnero** [rmagick-temp/rmagick#5]
http://pastebin.com/zY64KWAE

they are both installed... the image one was the one i decided to install...
I'm getting the above error message while trying to use DrQueueOnRails.
Not sure what is going on.

This error occurred while loading the following files:
# 

   RMagick
# 

   RMagick2.so
#

**Comment by baror** [comment]
Hi, deunnero -

A few questions:
a) What was the order that you installed ImageMagick/RMagick, and where did you install them?
b) Which version of ImageMagick are you using?
c) Which OS/version are you using?

When you install the RMagick gem, it compiles itself with whatever version of ImageMagick is on your machine. It then expects the version of ImageMagick to stay the same and to be available in your library path. So, if you install a new version of ImageMagick, you need to reinstall the RMagick gem to force it to recompile with the new ImageMagick. And, if you install ImageMagick to a strange location, you'll need to add it to your library path.

**Comment by deunnero** [comment]
A... ImageMagic First, Because RMagick would not install without imagemagick
      I used Yum install ImageMagick 
      I then used gem install rmagick

B.  Now i'm using 3.2.22

C. CentOS

uninstalled ImageMagick, and then uninstalled Rmagick.
Installed ImageMagick, and then installed RMagic.
Problem solved.
