### ISSUE TITLE
JRuby RMagic undefined_symbol: rb_framce_last_func

### ISSUE THREAD

**Issue by daveed** [rmagick-temp/rmagick#52]
I have an issue using the gem axlsx with JRuby. It seems to be an install problem.
Please have a look at https://github.com/randym/axlsx/issues/78 for my system details and error logs.

**Comment by vassilevsky** [comment]
This issue has been ported over to the maintained fork and closed without resolution:
https://github.com/gemhome/rmagick/issues/33
