### ISSUE TITLE
RVG :stroke_dasharray is not drawing correctly

### ISSUE THREAD

**Issue by grimm** [rmagick-temp/rmagick#56]
I can use stroke_dasharray horizontally with out problems, but when I draw it vertically an extra line gets inserted at the same coordinates.  Here is the command I'm using:

@canvas.line(x.to_i, top.to_i, x.to_i, bottom.to_i).styles( :stroke=>dstyle.color, :stroke_width=>dstyle.line_size, :stroke_dasharray=>[dstyle.lt_diva,dstyle.lt_divb])

both dstyle.lt_diva and dstyle.lt_divb are integers as well.  

Jason

**Comment by grimm** [comment]
Adding code versions:

ImageMagick - 6.7.0.10
rmagick - 2.13.1

**Comment by mmaiza** [comment]
Please specify the OS, rmagick version and imagemagick version that you are using.

Moncef

-----Original Message-----
From: Jason Grimes [mailto:reply@reply.github.com] 
Sent: Wednesday, July 18, 2012 10:18 PM
To: mmaiza
Subject: [rmagick] RVG :stroke_dasharray is not drawing correctly (#56)

I can use stroke_dasharray horizontally with out problems, but when I draw it vertically an extra line gets inserted at the same coordinates.  Here is the command I'm using:

@canvas.line(x.to_i, top.to_i, x.to_i, bottom.to_i).styles( :stroke=>dstyle.color, :stroke_width=>dstyle.line_size, :stroke_dasharray=>[dstyle.lt_diva,dstyle.lt_divb])

both dstyle.lt_diva and dstyle.lt_divb are integers as well.  

Jason

---

Reply to this email directly or view it on GitHub:
https://github.com/rmagick/rmagick/issues/56

**Comment by grimm** [comment]
Thanks Moncef, 

OS - Fedora 16
ImageMagick - 6.7.0.10
rmagick - 2.13.1

Jason

**Comment by grimm** [comment]
Well I was being dumb and forgot to set the fill to none.  It's working fine now thanks.

Jason

**Comment by mmaiza** [comment]
Excellent, I did intend to look into it tomorrow. Please close the case if you did not already. 

-----Original Message-----
