### ISSUE TITLE
Cannot install RMagic on Mountain Lion 10.8.2

### ISSUE THREAD

**Issue by rdudacz** [rmagick-temp/rmagick#61]
Hi guys,

I am trying to install rmagick on last OS X update, but I stuck there. When I run `gem install rmagick`, I get this error output:

---

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
    /Users/xxxxx/.rvm/rubies/ruby-1.9.3-p327/bin/ruby extconf.rb 
```

checking for Ruby version >= 1.8.5... yes
extconf.rb:128: Use RbConfig instead of obsolete and deprecated Config.
checking for clang... yes
checking for Magick-config... yes

Warning: Found more than one ImageMagick installation. This could cause problems at runtime.
         /usr/local/bin/Magick-config reports version 6.7.7 Q16 is installed in /usr/local/Cellar/imagemagick/6.7.7-6
         /opt/ImageMagick/bin/Magick-config reports version 6.7.8 Q16 is installed in /opt/ImageMagick
Using 6.7.7 Q16 from /usr/local/Cellar/imagemagick/6.7.7-6.

checking for ImageMagick version >= 6.4.9... yes
checking for HDRI disabled version of ImageMagick... yes
checking for stdint.h... yes
checking for sys/types.h... yes
checking for wand/MagickWand.h... yes
checking for InitializeMagick() in -lMagickCore... yes
checking for snprintf() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for AcquireImage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for AffinityImage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for AffinityImages() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for AutoGammaImageChannel() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for AutoLevelImageChannel() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for BlueShiftImage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for ConstituteComponentTerminus() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for DeskewImage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for EncipherImage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for EqualizeImageChannel() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for FloodfillPaintImage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for FunctionImageChannel() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for GetAuthenticIndexQueue() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for GetAuthenticPixels() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for GetImageAlphaChannel() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for GetVirtualPixels() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for LevelImageColors() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for LevelColorsImageChannel() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for LevelizeImageChannel() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for LiquidRescaleImage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for MagickLibAddendum() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for OpaquePaintImageChannel() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for QueueAuthenticPixels() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for RemapImage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for RemoveImageArtifact() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for SelectiveBlurImageChannel() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for SetImageAlphaChannel() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for SetImageArtifact() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for SetMagickMemoryMethods() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for SparseColorImage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for SyncAuthenticPixels() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for TransparentPaintImage() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for TransparentPaintImageChroma() in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for QueryMagickColorname() new signature... yes
checking for Image.type in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for DrawInfo.kerning in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for DrawInfo.interline_spacing in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for DrawInfo.interword_spacing in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for DitherMethod in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for MagickFunction in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for ImageLayerMethod in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for long double in assert.h,ctype.h,stdio.h,stdlib.h,math.h,time.h,stdint.h,sys/types.h,wand/MagickWand.h... yes
checking for AlphaChannelType.CopyAlphaChannel... yes
checking for AlphaChannelType.BackgroundAlphaChannel... yes
checking for CompositeOperator.BlurCompositeOp... yes
checking for CompositeOperator.DistortCompositeOp... yes
checking for CompositeOperator.LinearBurnCompositeOp... yes
checking for CompositeOperator.LinearDodgeCompositeOp... yes
checking for CompositeOperator.MathematicsCompositeOp... yes
checking for CompositeOperator.PegtopLightCompositeOp... yes
checking for CompositeOperator.PinLightCompositeOp... yes
checking for CompositeOperator.VividLightCompositeOp... yes
checking for CompressionType.DXT1Compression... yes
checking for CompressionType.DXT3Compression... yes
checking for CompressionType.DXT5Compression... yes
checking for CompressionType.ZipSCompression... yes
checking for CompressionType.PizCompression... yes
checking for CompressionType.Pxr24Compression... yes
checking for CompressionType.B44Compression... yes
checking for CompressionType.B44ACompression... yes
checking for DistortImageMethod.BarrelDistortion... yes
checking for DistortImageMethod.BarrelInverseDistortion... yes
checking for DistortImageMethod.BilinearForwardDistortion... yes
checking for DistortImageMethod.BilinearReverseDistortion... yes
checking for DistortImageMethod.DePolarDistortion... yes
checking for DistortImageMethod.PolarDistortion... yes
checking for DistortImageMethod.PolynomialDistortion... yes
checking for DistortImageMethod.ShepardsDistortion... yes
checking for DitherMethod.NoDitherMethod... yes
checking for FilterTypes.KaiserFilter... yes
checking for FilterTypes.WelshFilter... yes
checking for FilterTypes.ParzenFilter... yes
checking for FilterTypes.LagrangeFilter... yes
checking for FilterTypes.BohmanFilter... yes
checking for FilterTypes.BartlettFilter... yes
checking for FilterTypes.SentinelFilter... yes
checking for MagickEvaluateOperator.PowEvaluateOperator... yes
checking for MagickEvaluateOperator.LogEvaluateOperator... yes
checking for MagickEvaluateOperator.ThresholdEvaluateOperator... yes
checking for MagickEvaluateOperator.ThresholdBlackEvaluateOperator... yes
checking for MagickEvaluateOperator.ThresholdWhiteEvaluateOperator... yes
checking for MagickEvaluateOperator.GaussianNoiseEvaluateOperator... yes
checking for MagickEvaluateOperator.ImpulseNoiseEvaluateOperator... yes
checking for MagickEvaluateOperator.LaplacianNoiseEvaluateOperator... yes
checking for MagickEvaluateOperator.MultiplicativeNoiseEvaluateOperator... yes
checking for MagickEvaluateOperator.PoissonNoiseEvaluateOperator... yes
checking for MagickEvaluateOperator.UniformNoiseEvaluateOperator... yes
checking for MagickEvaluateOperator.CosineEvaluateOperator... yes
checking for MagickEvaluateOperator.SineEvaluateOperator... yes
checking for MagickEvaluateOperator.AddModulusEvaluateOperator... yes
checking for MagickFunction.ArcsinFunction... yes
checking for MagickFunction.ArctanFunction... yes
checking for MagickFunction.PolynomialFunction... yes
checking for MagickFunction.SinusoidFunction... yes
checking for ImageLayerMethod.FlattenLayer... yes
checking for ImageLayerMethod.MergeLayer... yes
checking for ImageLayerMethod.MosaicLayer... yes
checking for ImageLayerMethod.TrimBoundsLayer... yes
checking for VirtualPixelMethod.HorizontalTileVirtualPixelMethod... yes
checking for VirtualPixelMethod.VerticalTileVirtualPixelMethod... yes
checking for VirtualPixelMethod.HorizontalTileEdgeVirtualPixelMethod... yes
checking for VirtualPixelMethod.VerticalTileEdgeVirtualPixelMethod... yes
checking for VirtualPixelMethod.CheckerTileVirtualPixelMethod... yes
checking for ruby/io.h... yes
checking for rb_frame_this_func() in ruby.h,ruby/io.h... yes
creating extconf.h
creating Makefile
# 

Sun 23Dec12 12:18:17
This installation of RMagick 2.13.1 is configured for
# Ruby 1.9.3 (x86_64-darwin12.2.0) and ImageMagick 6.7.7 Q16 

make
compiling rmagick.c
compiling rmdraw.c
compiling rmenum.c
rmenum.c:450:13: warning: 4 enumeration values not handled in switch: 'DivideSrcCompositeOp', 'MinusSrcCompositeOp', 'DarkenIntensityCompositeOp'... [-Wswitch]
    switch (op)
            ^
rmenum.c:565:13: warning: enumeration values 'LZMACompression', 'JBIG1Compression', and 'JBIG2Compression' not handled in switch [-Wswitch]
    switch (ct)
            ^
rmenum.c:674:12: warning: 7 enumeration values not handled in switch: 'SincFastFilter', 'LanczosSharpFilter', 'Lanczos2Filter'... [-Wswitch]
    switch(type)
           ^
rmenum.c:922:12: warning: 5 enumeration values not handled in switch: 'Average9InterpolatePixel', 'Average16InterpolatePixel', 'BlendInterpolatePixel'... [-Wswitch]
    switch(interpolate)
           ^
4 warnings generated.
compiling rmfill.c
compiling rmilist.c
rmilist.c:448:12: warning: 'MapImages' is deprecated [-Wdeprecated-declarations](void) MapImages(new_images, map, dither);
           ^
/usr/local/Cellar/imagemagick/6.7.7-6/include/ImageMagick/magick/deprecate.h:197:3: note: 'MapImages' declared here
  MapImages(Image _,const Image *,const MagickBooleanType)
  ^
1 warning generated.
compiling rmimage.c
rmimage.c:8155:12: warning: 'MapImage' is deprecated [-Wdeprecated-declarations](void) MapImage(new_image, map, dither);
           ^
/usr/local/Cellar/imagemagick/6.7.7-6/include/ImageMagick/magick/deprecate.h:195:3: note: 'MapImage' declared here
  MapImage(Image *,const Image *,const MagickBooleanType)
  ^
rmimage.c:10701:17: warning: 'RecolorImage' is deprecated [-Wdeprecated-declarations]
    new_image = RecolorImage(image, order, matrix, &exception);
                ^
/usr/local/Cellar/imagemagick/6.7.7-6/include/ImageMagick/magick/deprecate.h:139:4: note: 'RecolorImage' declared here
  *RecolorImage(const Image *,const size_t,const double *,ExceptionInfo *)
   ^
2 warnings generated.
compiling rminfo.c
compiling rmmain.c
compiling rmmontage.c
compiling rmpixel.c
compiling rmstruct.c
compiling rmutil.c
rmutil.c:1612:43: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
    rb_raise(Class_FatalImageMagickError, GetLocaleExceptionMessage(severity, reason));
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rmutil.c:1652:20: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
        rb_warning(msg);
                   ^~~
2 warnings generated.
linking shared-object RMagick2.bundle
ld: file not found: /usr/local/lib/libfreetype.6.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *_\* [RMagick2.bundle] Error 1

Gem files will remain installed in /Users/xxxxx/.rvm/gems/ruby-1.9.3-p327/gems/rmagick-2.13.1 for inspection.
Results logged to /Users/xxxxx/.rvm/gems/ruby-1.9.3-p327/gems/rmagick-2.13.1/ext/RMagick/gem_make.out
An error occurred while installing rmagick (2.13.1), and Bundler cannot continue.
Make sure that `gem install rmagick -v '2.13.1'` succeeds before bundling.

---

I spent more than a day on this issue, but still don't see the right direction how to figure it out... I will appreciate every advice.

Thanks

**Comment by specialorange** [comment]
Same issue

**Comment by mcdickenson** [comment]
+1

**Comment by fringley** [comment]
me too

**Comment by filipechagas** [comment]
Find the solution here: https://github.com/rmagick/rmagick/issues/60#issuecomment-11541042

```
cd /usr/local/Cellar/imagemagick/6.8.0-10/lib/
ln -s libMagick++-Q16.7.dylib   libMagick++.dylib
ln -s libMagickCore-Q16.7.dylib libMagickCore.dylib
ln -s libMagickWand-Q16.7.dylib libMagickWand.dylib
gem install rmagick
```

**Comment by gregory** [comment]
+1

**Comment by jbowles** [comment]
+1 thanks filipechagas

**Comment by mmaiza** [comment]
I do not have a Mac and so could not test this but the new release should fix this.

**Comment by gregory** [comment]
@mmaiza [it doesn't](http://pastebin.com/iBkKK9V6) ...

**Comment by rmagick-temp** [comment]
Thanks for including the pastie. If you check you will see that it is using 2.13.1 the old version. At the time I had it only available from github only. I have pushed it to rubygems since so please trying again now it will use 2.13.2.

Moncef

**Comment by msalahat** [comment]
I tried all the solutions above and still got the same error :(

Can't install RMagick 2.13.2. Can't find MagickWand.h.

**Comment by msalahat** [comment]
I found the fix here
http://superuser.com/questions/361435/i-have-compiled-imagemagick-on-my-centos-and-rmagick-wont-install

**Comment by mmaiza** [comment]
This does not tell me anything about what you are doing. Paste your commands and the results so we can help you.

Moncef

**Comment by realdlee** [comment]
After upgrading to Mountain Lion, I'm experiencing similar problems.  I've attempted most (or all) of the fixes I've come across.  I tried to set the gem 'rmagick' to the latest version but it doesn't bundle install.  

Installing rmagick (2.13.2) with native extensions 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
    /Users/DL/.rvm/rubies/ruby-1.9.3-p0/bin/ruby extconf.rb 
```

checking for Ruby version >= 1.8.5... yes
checking for /usr/bin/gcc-4.2... no
No C compiler found in ${ENV['PATH']}. See mkmf.log for details.
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

If I use the old version of rmagick, then when attempting to run 'rails s', I get: 

Exiting
/Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- RMagick (LoadError)
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in`block in require'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in`require'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@aptjoy/gems/carrierwave-0.7.1/lib/carrierwave/processing/rmagick.rb:7:in `rescue in <top (required)>'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@aptjoy/gems/carrierwave-0.7.1/lib/carrierwave/processing/rmagick.rb:4:in`<top (required)>'
    from /Users/DL/Desktop/rails_projects/aptjoy/config/initializers/carrierwave.rb:2:in `<module:CarrierWave>'
    from /Users/DL/Desktop/rails_projects/aptjoy/config/initializers/carrierwave.rb:1:in`<top (required)>'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `load'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in`block in load'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in`load'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/engine.rb:587:in`each'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/engine.rb:587:in `block in <class:Engine>'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/initializable.rb:30:in`instance_exec'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/initializable.rb:30:in `run'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/initializable.rb:55:in`block in run_initializers'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/initializable.rb:54:in `each'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/initializable.rb:54:in`run_initializers'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/application.rb:136:in `initialize!'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in`method_missing'
    from /Users/DL/Desktop/rails_projects/aptjoy/config/environment.rb:5:in `<top (required)>'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in`require'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in`load_dependency'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from /Users/DL/Desktop/rails_projects/aptjoy/config.ru:3:in`block in <main>'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@aptjoy/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@aptjoy/gems/rack-1.4.5/lib/rack/builder.rb:51:in`initialize'
    from /Users/DL/Desktop/rails_projects/aptjoy/config.ru:in `new'
    from /Users/DL/Desktop/rails_projects/aptjoy/config.ru:in`<main>'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@aptjoy/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@aptjoy/gems/rack-1.4.5/lib/rack/builder.rb:40:in`parse_file'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@aptjoy/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/commands/server.rb:46:in`app'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@aptjoy/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@aptjoy/gems/rack-1.4.5/lib/rack/server.rb:254:in`start'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/commands/server.rb:70:in `start'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/commands.rb:55:in`block in <top (required)>'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/commands.rb:50:in `tap'
    from /Users/DL/.rvm/gems/ruby-1.9.3-p0@global/gems/railties-3.2.12/lib/rails/commands.rb:50:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

One thing I haven't tried yet is: rvm install 1.9.3 --with-gcc=clang

**Comment by mmaiza** [comment]
Please do not comment on closed issues. Your problem is that your environment is not setup properly. It says that no C compiler was found. This means that either the path or the compiler is missing. Locate your compiler and make sure it is in your path.

**Comment by owocki** [comment]
thank you @filipechagas

**Comment by mrmins** [comment]
I have a problem, 
checking for wand/MagickWand.h... no
Can't install RMagick 2.13.2. Can't find MagickWand.h.

Why my gem install cant find wand/MagickWand.h ?
