### ISSUE TITLE
RMagick 2.13.2 on Windows 7 x64

### ISSUE THREAD

**Issue by bodrovis** [rmagick-temp/rmagick#66]
Hello. I just noticed that RMagick was updated to 2.13.2 and that it should support ImageMagick 6.8. So i uninstalled my old ImageMagick, downloaded a new one (6.8.2-3-Q16-x64-dll) and installed in with C/C++ headers. Then i tried to install RMagick using instructions found in the Wiki (it helped me to install rmagick 2.13.1), but got the following error:

``` ruby
======================================================================
Mon 04Feb13 15:18:18
This installation of RMagick 2.13.2 is configured for
Ruby 1.9.3 (i386-mingw32) and ImageMagick 6.8.2
======================================================================



make
generating RMagick2-i386-mingw32.def
compiling rmagick.c
In file included from P:\ImageMagick/include/magick/magick-config.h:25:0,
                 from P:\ImageMagick/include/magick/MagickCore.h:29,
                 from rmagick.h:47,
                 from rmagick.c:13:
P:\ImageMagick/include/magick/magick-baseconfig.h:181:14: error: conflicting types for 'ssize_t'
p:\devkit\mingw\bin\../lib/gcc/mingw32/4.5.2/../../../../include/sys/types.h:118:18: note: previous declaration of 'ssize_t' was here
rmagick.c: In function 'Magick_colors':
rmagick.c:42:5: warning: passing argument 2 of 'GetColorInfoList' from incompatible pointer type
P:\ImageMagick/include/magick/color.h:75:5: note: expected 'size_t *' but argument is of type 'long unsigned int *'
rmagick.c: In function 'Magick_fonts':
rmagick.c:90:5: warning: passing argument 2 of 'GetTypeInfoList' from incompatible pointer type
P:\ImageMagick/include/magick/type.h:98:5: note: expected 'size_t *' but argument is of type 'long unsigned int *'
rmagick.c: In function 'Magick_init_formats':
rmagick.c:178:5: warning: passing argument 2 of 'GetMagickInfoList' from incompatible pointer type
P:\ImageMagick/include/magick/magick.h:125:5: note: expected 'size_t *' but argument is of type 'long unsigned int *'
make: *** [rmagick.o] Error 1
```

Exactly the same error i got when trying to use ImageMagick x86. My Ruby version is 1.9.3-p374. I recall, that when trying to use ImageMagick 6.8 with older rmagick 2.13.1 i got the same (or near the same) error about conflicting types.

Any clues about this issue?

**Comment by rmagick-temp** [comment]
I intend to address the type incompatibilities next. On Linux they do not cause the build to fail but it appears that they do on windows. I will try on windows and keep you updated.

**Comment by aplatypus** [comment]
Hi there,

I have the **ruby windows installer** up and running '_nice_' under Windows 7 64-bit.  I have ImageMagick installed and we have the C headers.  Unfortunately the gem won't build for me.  

I think we need some instructions for how to install the gem and ponit to the .h files and .lib files.

---

```
ruby -S gem install rmagick
Fetching: rmagick-2.13.2.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
        ERROR: Failed to build gem native extension.

    B:/lang/ruby/v02.00/bin/ruby.exe extconf.rb

checking for Ruby version >= 1.8.5... yes
Invalid drive specification.
Unable to get ImageMagick version

*** extconf.rb failed ***

Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=B:/lang/ruby/v02.00/bin/ruby

Gem files will remain installed in B:/lang/ruby/v02.00/lib/ruby/gems/2.0.0/gems/rmagick-2.13.2 for inspection.
Results logged to B:/lang/ruby/v02.00/lib/ruby/gems/2.0.0/gems/rmagick-2.13.2/ext/RMagick/gem_make.out
```

---
- Windows 7 sp1
- ruby 2

**Comment by bodrovis** [comment]
@aplatypus Version 2.13.2 is not compatible with Windows. Use version 2.13.1 and these instructions: https://github.com/rmagick/rmagick/wiki It worked for me, though I really had hard times when installing this gem on Windows.

Please not that 2.13.1 will not work with latest ImageMagick, you should use 6.7.9.

**Comment by ThaDafinser** [comment]
@bodrovis @aplatypus i just successfully installed it (but was really a pain....)

Versions
- Imagemagick 6.7.9 Q16 (http://ftp.sunet.se/pub/multimedia/graphics/ImageMagick/binaries/ImageMagick-6.7.9-9-Q16-windows-dll.exe)
- rmagick 2.13.2
- win7

**Comment by abaumgaertner** [comment]
see for a solution gemhome/rmagick#175

for version 2.13.2 with mingw on windows
unpack the gem, fix the extconf.rb
change this line 

```
elsif RUBY_PLATFORM =~ /mingw/  # mingw
  `convert -version` =~ /Version: ImageMagick (\d+\.\d+\.\d+)-\d+ /
  abort "Unable to get ImageMagick version" unless $1
  $magick_version = $1
  $LOCAL_LIBS = '-lCORE_RL_magick_ -lX11'
```

to  
      $LOCAL_LIBS = '-lCORE_RL_magick_' 

Remove the x11 reference - this was breaking my efforts to get rmagick running.
and the latest version supported is 6.7.9.9

I would go for https://github.com/gemhome/rmagick now ...

**Comment by 62mkv** [comment]
I have to admit, same problem occurs with rmagick 2.13.4. I had an unlucky assignment to install Redmine 2.6.9. under Windows 10, and while with rmagick 2.16.0 it occurred according to the wiki, with 2.13.4 which was in Gemfile for RM 2.6.9, this sh*t with -lX11 was happening all the time. This thread is COOL!
