### ISSUE TITLE
This installation of RMagick was configured with ImageMagick 6.6.1 but ImageMagick 6.5.9-3 is in use.

### ISSUE THREAD

**Issue by jezcaudle** [rmagick-temp/rmagick#7]
Hi, followed the instructions for installing ImageMagick and rmagic from this page:

http://rmagick.rubyforge.org/install-osx.html

And when I execute the following:

irb -rubygems -r RMagick

I get the error:

/usr/local/lib/ruby/gems/1.8/gems/rmagick-2.13.1/lib/RMagick2.bundle:RuntimeError: This installation of RMagick was configured with ImageMagick 6.6.1 but ImageMagick 6.5.9-3 is in use.

I have removed the rmagick gem:

gem uninstall rmagick

and reinstalled it, but I get the same error.

Some where the version of ImageMagic the gem build is picking up is correct but Ruby and/or the OS are picking up the old version. But I don't know how to change Ruby and/or the OS to "see" the correct version.

According to MacPorts I have 6.6.1 installed. So where is version 6.5.9-3 then?

identify -version

returns 

Version: ImageMagick 6.6.1-5

Any clues to what I need to do here? I did have 6.5 installed earlier so I deleted the installation files in /opt/local/var/macports/software/ImageMagick/6.5.9-0_0+q16, removed the gem and reinstalled.

And then got the same error.

I have run out of things to try ...

Thanks.

**Comment by jezcaudle** [comment]
Okay, I have two versions of ImageMagick on my Mac. One that I installed via MacPorts and one that I must have installed a while ago - I have no recollection. It appears that:

gem install rmagick 

finds the version of ImageMagick installed by MacPorts (/opt/local/bin) and builds against that but when I invoke irb with:

irb -rubygems -r RMagick

irb uses the version is /usr/local/bin, the previous and wrong version. I have checked my bash path and /opt comes first.

So I asume that as IRB is invoked it goes through different paths looking for stuff and it is finding the old version of ImageMagic. Now all I need to do is find the files and delete them. Any help here would be appreciated.

**Comment by jezcaudle** [comment]
I have removed the older version of ImageMagic and now only have the MacPorts version. I am going to remove that and try the out of date script for installing the Ruby Gem.

I'm getting the feeling that I'm on my own here.

**Comment by jezcaudle** [comment]
Okay - I managed to sort out the problem. Nuke MacPorts including in your .profile, reboot and then install ImageMagick using a script I found and then gem install rmagick

**Comment by bentomas** [comment]
Hey sorry you felt like you were alone here!  Omer and I can get pretty busy at times and we always don't get back to people right away.

I'm glad you figured it out!

**Comment by jezcaudle** [comment]
I was having a drama queen moment. You guys do a fantastic job for no money. If you really do want to make the GEM idiot proof - idiots like me who have ImageMagic installed twice - then the build process or the run process needs to change. You guys set your own priorities. Thanks for the hard work.
