### ISSUE TITLE
Install problem with rmagick

### ISSUE THREAD

**Issue by jplethier** [rmagick-temp/rmagick#88]
When I try to install the rmagick gem, I am getting this error:

gem install rmagick -v '2.13.1'
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
    ERROR: Failed to build gem native extension.

```
    /Users/jplethier/.rvm/rubies/ruby-1.9.3-p392/bin/ruby extconf.rb
```

checking for Ruby version >= 1.8.5... yes
extconf.rb:128: Use RbConfig instead of obsolete and deprecated Config.
checking for /usr/local/bin/gcc-4.2... yes
checking for Magick-config... yes
checking for ImageMagick version >= 6.4.9... yes
checking for HDRI disabled version of ImageMagick... yes
checking for stdint.h... yes
checking for sys/types.h... yes
checking for wand/MagickWand.h... yes
checking for InitializeMagick() in -lMagickCore... no
checking for InitializeMagick() in -lMagick... no
checking for InitializeMagick() in -lMagick++... no
Can't install RMagick  2.13.1. Can't find the ImageMagick library or one of the dependent libraries. Check the mkmf.log file for more detailed information.

**Comment by mmaiza** [comment]
Closing this is no longer an issue
